# Default values for multicluster-controlplane.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: quay.io/stolostron/multicluster-controlplane:latest
imagePullPolicy: IfNotPresent

replicas: 1

features: "DefaultClusterSet=true,ManagedClusterAutoApproval=true"

# TODO: use controlplane:bootstrap-user as default
autoApprovalBootstrapUsers: "system:admin"

# TODO: should add restriction while enable selfmanagement
enableSelfManagement: false

apiserver:
  externalHostname: ""
  ca: ""
  cakey: ""
etcd:
  mode: "embed"
  servers: []
  ca: ""
  cert: "" 
  certkey: "" 

pvc:
  storageCapacity: 10Gi
  storageClassName: ""
  selector: {}

route:
  enabled: true
  # for route, we may have more config to support in the future

loadbalancer:
  enabled: false
  # TODO: is it any different with externalHostname?
  baseDomain: ""  #e,g, *.aws.xxx

nodeport:
  enabled: false
  port: 30443
